# Generated by Django 4.2.3 on 2024-04-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('geography', 'Geography'), ('science', 'Science')], default='geography', max_length=100),
            preserve_default=False,
        ),
    ]
