version: '3.8'
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=emotive
      - POSTGRES_USER=emotive
      - POSTGRES_PASSWORD=emotive
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=take_home.settings
      - DJANGO_LOG_LEVEL=DEBUG
      - ENV=local
      - POSTGRES_NAME=emotive
      - POSTGRES_USER=emotive
      - POSTGRES_PASS=emotive
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./tests:/tests
    command: runserver

volumes:
  db_data:
    driver: local
